#!/bin/bash

set -uevo pipefail
git submodule update --init python.git
cat >> python.git/Modules/Setup << EOF
*shared*
*static*
_random _randommodule.c	# Random number generator
_datetime _datetimemodule.c	# datetime accelerator
_struct _struct.c	# binary structure packing/unpacking
math mathmodule.c _math.c # -lm # math library functions, e.g. sin
_csv _csv.c
EOF
cd python.git
./configure --disable-shared --disable-optimizations --disable-ipv6 --prefix=$PWD/../install.dir LDFLAGS="--static"
make LDFLAGS="-static" LINKFORSHARED=" "

