#!/bin/bash
# Run `with_pyenv pyenv update` or remove ./.pyenv or your $PYENV_ROOT to update environment
#
SCRIPT_DIR="$(readlink -f $(dirname ${BASH_SOURCE[0]}))"
export PYENV_VERSION=3.5.6
export PYENV_ROOT="${PYENV_ROOT:-${SCRIPT_DIR}/.pyenv}"
if [ ! -d ${PYENV_ROOT} ] ; then
    wget -O-  https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
#else
#    ${PYENV_ROOT}/bin/pyenv update
fi
export PATH="${PYENV_ROOT}/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
CFLAGS='-O2 -g -fPIC' pyenv install -k -s $PYENV_VERSION
export PKG_CONFIG_PATH=$(python3-config --prefix)/lib/pkgconfig
if (( "$#" == 0 )) ; then
	echo "Use ${BASH_SOURCE[0]} <bash command like for 'bash -c'>"
	echo "Example: "
	echo "${BASH_SOURCE[0]} \"echo '\$PKG_CONFIG_PATH' && python --version\""
else
	exec bash -c "$@"
fi
